### ISSUE TITLE
Problem of implementation

### ISSUE THREAD

**Issue by Natherc** [noomerzx/vue-barcode-scanner#12]
Hye there, i don't undestand very well how you must implement that ? 
I mean,I created a component just for that purpose but i don't know what i'm supposed to see ? I just noticed that it detects "Enter" inputs.
Does it use the camera or some sort just like QuaggaJS or must I ad an video element in the template ?

**Comment by noomerzx** [comment]
It's just use for a barcode scanner (hardware) not for a camera like Quagga. Normally if you wanna use barcode scanner for your web application such as POS system, You need to implement a input listener by yourself to catch the event and sometimes it complicated because when scanner scan a barcode it's scanned each input continuously. 

For example 

if Barcode = "1x2x333xx" when you scanner is done, Your listener will catched event 9 times and you need to concat those string by yourself.

Others things you need to know.
- All scanner (hardware) in the world does not the same behavior when you scanning a thing, Some scanner have a special character input for something and you need to catched that and do something in your listener (if you implement by yourself)
- Some scanner have last key as TAB or ENTER or sometime nothing on the last key
- Some time you need to separating the input by human or scanner
- That a lot of thing you need to handle by yourself

What this plugin do for you.
I thing you'll understand this plugin by reading our readme again after my explaination on this comment.

But if not i'll tell you shortly..
This plugin provide a listener for you and handle the problem about special charactor or anything and just return the final result for you in 1 line of string.

This plugin wrote in Vue.js way, So it's more convenience and easy to use for Vue.js Application instead of implementing your own or use other 3rd libs.
